name: cd

on:
  push:
    branches: [main, develop2]
  pull_request:
    branches: [main, develop2]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
